In [ ]:
#Kaggle Set
#About This Data
#This is a list of over 18,000 restaurants in the US that serve vegetarian or vegan food provided by Datafiniti's Business Database. The dataset includes address, city, state, business name, business categories, menu data, phone numbers, and more.

#Note that this is a sample of a large dataset. The full dataset is available through Datafiniti.

In [128]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

restaurants = pd.read_csv('Datafiniti_Vegetarian_and_Vegan_Restaurants.csv')

In [129]:
print(len(restaurants))
#10000 entries
print(restaurants.head(5))

10000
                     id             dateAdded           dateUpdated  \
0  AVwd3yXEkufWRAb59-sH  2016-04-22T02:47:48Z  2018-09-10T21:00:49Z
1  AVwd3yXEkufWRAb59-sH  2016-04-22T02:47:48Z  2018-09-10T21:00:49Z
2  AVwd3yXEkufWRAb59-sH  2016-04-22T02:47:48Z  2018-09-10T21:00:49Z
3  AVwd3yXEkufWRAb59-sH  2016-04-22T02:47:48Z  2018-09-10T21:00:49Z
4  AVwd3yXEkufWRAb59-sH  2016-04-22T02:47:48Z  2018-09-10T21:00:49Z

              address                                         categories  \
0  1045 San Pablo Ave  Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
1  1045 San Pablo Ave  Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
2  1045 San Pablo Ave  Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
3  1045 San Pablo Ave  Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
4  1045 San Pablo Ave  Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...

               primaryCategories    city claimed country  \
0  Accommodation & Food Services  Albany     NaN      US
1  Accommodation & Food Services  Albany     NaN      US
2  Accommodation & Food Services  Albany     NaN      US
3  Accommodation & Food Services  Albany     NaN      US
4  Accommodation & Food Services  Albany     NaN      US

                        cuisines  descriptions.dateSeen  \
0  Thai,Asian/Pacific,Vegetarian                    NaN
1  Thai,Asian/Pacific,Vegetarian                    NaN
2  Thai,Asian/Pacific,Vegetarian                    NaN
3  Thai,Asian/Pacific,Vegetarian                    NaN
4  Thai,Asian/Pacific,Vegetarian                    NaN

   descriptions.sourceURLs  descriptions.value facebookPageURL  features.key  \
0                      NaN                 NaN             NaN           NaN
1                      NaN                 NaN             NaN           NaN
2                      NaN                 NaN             NaN           NaN
3                      NaN                 NaN             NaN           NaN
4                      NaN                 NaN             NaN           NaN

   features.value  hours.day  hours.dept  hours.hour  \
0             NaN        NaN         NaN         NaN
1             NaN        NaN         NaN         NaN
2             NaN        NaN         NaN         NaN
3             NaN        NaN         NaN         NaN
4             NaN        NaN         NaN         NaN

                                           imageURLs isClosed  \
0  https://igx.4sqi.net/img/general/600x600/o_h1i...      NaN
1  https://igx.4sqi.net/img/general/600x600/o_h1i...      NaN
2  https://igx.4sqi.net/img/general/600x600/o_h1i...      NaN
3  https://igx.4sqi.net/img/general/600x600/o_h1i...      NaN
4  https://igx.4sqi.net/img/general/600x600/o_h1i...      NaN

                                       keys  languagesSpoken   latitude  \
0  us/ca/albany/1045sanpabloave/-1106202297              NaN  37.885131
1  us/ca/albany/1045sanpabloave/-1106202297              NaN  37.885131
2  us/ca/albany/1045sanpabloave/-1106202297              NaN  37.885131
3  us/ca/albany/1045sanpabloave/-1106202297              NaN  37.885131
4  us/ca/albany/1045sanpabloave/-1106202297              NaN  37.885131

    longitude                                        menuPageURL  \
0 -122.297013  http://www.singlepage.com/ruen-pair-authentic-...
1 -122.297013  http://www.singlepage.com/ruen-pair-authentic-...
2 -122.297013  http://www.singlepage.com/ruen-pair-authentic-...
3 -122.297013  http://www.singlepage.com/ruen-pair-authentic-...
4 -122.297013  http://www.singlepage.com/ruen-pair-authentic-...

   menus.amountMax  menus.amountMin menus.category menus.currency  \
0            13.95             3.75            NaN            USD
1            13.95             3.75            NaN            USD
2            13.95             3.75            NaN            USD
3             8.95             8.95            NaN            USD
4            13.95             3.75            NaN            USD

             menus.dateSeen                             menus.description  \
0  2016-04-22T02:48:00.000Z  Squash, carrots, butternut squash and potato
1  2016-04-22T02:48:00.000Z                    With wild blend brown rice
2  2016-04-22T02:48:00.000Z                                           NaN
3  2016-04-22T02:48:00.000Z                                           NaN
4  2016-04-22T02:48:00.000Z             With vinegar tahini beet dressing

                              menus.name  \
0                          Baked Kabocha
1                 Short Grain Brown Rice
2                 Green Bean Veggie Soup
3  Steamed Broccoli, Carrots and Turnips
4                      Mixed Green Salad

                                    menus.sourceURLs                 name  \
0  https://foursquare.com/v/potala-organic-cafe/4...  Potala Organic Cafe
1  https://foursquare.com/v/potala-organic-cafe/4...  Potala Organic Cafe
2  https://foursquare.com/v/potala-organic-cafe/4...  Potala Organic Cafe
3  https://foursquare.com/v/potala-organic-cafe/4...  Potala Organic Cafe
4  https://foursquare.com/v/potala-organic-cafe/4...  Potala Organic Cafe

  paymentTypes          phones postalCode priceRangeCurrency  priceRangeMin  \
0          NaN  (510) 528-2375      94706                NaN            NaN
1          NaN  (510) 528-2375      94706                NaN            NaN
2          NaN  (510) 528-2375      94706                NaN            NaN
3          NaN  (510) 528-2375      94706                NaN            NaN
4          NaN  (510) 528-2375      94706                NaN            NaN

   priceRangeMax province  sic  \
0            NaN       CA  NaN
1            NaN       CA  NaN
2            NaN       CA  NaN
3            NaN       CA  NaN
4            NaN       CA  NaN

                                          sourceURLs twitter  \
0  https://foursquare.com/v/potala-organic-cafe/4...     NaN
1  https://foursquare.com/v/potala-organic-cafe/4...     NaN
2  https://foursquare.com/v/potala-organic-cafe/4...     NaN
3  https://foursquare.com/v/potala-organic-cafe/4...     NaN
4  https://foursquare.com/v/potala-organic-cafe/4...     NaN

                                 websites  yearOpened
0  http://www.potala.us/,http://potala.us         NaN
1  http://www.potala.us/,http://potala.us         NaN
2  http://www.potala.us/,http://potala.us         NaN
3  http://www.potala.us/,http://potala.us         NaN
4  http://www.potala.us/,http://potala.us         NaN

In [130]:
print(restaurants.columns)

Index(['id', 'dateAdded', 'dateUpdated', 'address', 'categories',
       'primaryCategories', 'city', 'claimed', 'country', 'cuisines',
       'descriptions.dateSeen', 'descriptions.sourceURLs',
       'descriptions.value', 'facebookPageURL', 'features.key',
       'features.value', 'hours.day', 'hours.dept', 'hours.hour', 'imageURLs',
       'isClosed', 'keys', 'languagesSpoken', 'latitude', 'longitude',
       'menuPageURL', 'menus.amountMax', 'menus.amountMin', 'menus.category',
       'menus.currency', 'menus.dateSeen', 'menus.description', 'menus.name',
       'menus.sourceURLs', 'name', 'paymentTypes', 'phones', 'postalCode',
       'priceRangeCurrency', 'priceRangeMin', 'priceRangeMax', 'province',
       'sic', 'sourceURLs', 'twitter', 'websites', 'yearOpened'],
      dtype='object')

In [131]:
restaurants_info_needed = restaurants[["name","address" , "city","province","cuisines"]]
print(restaurants_info_needed.head())

                  name             address    city province  \
0  Potala Organic Cafe  1045 San Pablo Ave  Albany       CA
1  Potala Organic Cafe  1045 San Pablo Ave  Albany       CA
2  Potala Organic Cafe  1045 San Pablo Ave  Albany       CA
3  Potala Organic Cafe  1045 San Pablo Ave  Albany       CA
4  Potala Organic Cafe  1045 San Pablo Ave  Albany       CA

                        cuisines
0  Thai,Asian/Pacific,Vegetarian
1  Thai,Asian/Pacific,Vegetarian
2  Thai,Asian/Pacific,Vegetarian
3  Thai,Asian/Pacific,Vegetarian
4  Thai,Asian/Pacific,Vegetarian

In [132]:
duplicates = restaurants_info_needed.duplicated()
print(duplicates.value_counts())

True     9789
False     211
dtype: int64

In [133]:
print(restaurants_info_needed[1:100])
#a lot of duplicated restaurants. Will remove.

                   name                   address       city province  \
1   Potala Organic Cafe        1045 San Pablo Ave     Albany       CA
2   Potala Organic Cafe        1045 San Pablo Ave     Albany       CA
3   Potala Organic Cafe        1045 San Pablo Ave     Albany       CA
4   Potala Organic Cafe        1045 San Pablo Ave     Albany       CA
5      Passage To India  16411 Bernardo Center Dr  San Diego       CA
6      Passage To India  16411 Bernardo Center Dr  San Diego       CA
7      Passage To India  16411 Bernardo Center Dr  San Diego       CA
8      Passage To India  16411 Bernardo Center Dr  San Diego       CA
9      Passage To India  16411 Bernardo Center Dr  San Diego       CA
10     Passage To India  16411 Bernardo Center Dr  San Diego       CA
11     Passage To India  16411 Bernardo Center Dr  San Diego       CA
12     Passage To India  16411 Bernardo Center Dr  San Diego       CA
13     Passage To India  16411 Bernardo Center Dr  San Diego       CA
14     Passage To India  16411 Bernardo Center Dr  San Diego       CA
15     Passage To India  16411 Bernardo Center Dr  San Diego       CA
16     Passage To India  16411 Bernardo Center Dr  San Diego       CA
17     Passage To India  16411 Bernardo Center Dr  San Diego       CA
18     Passage To India  16411 Bernardo Center Dr  San Diego       CA
19     Passage To India  16411 Bernardo Center Dr  San Diego       CA
20     Passage To India  16411 Bernardo Center Dr  San Diego       CA
21     Passage To India  16411 Bernardo Center Dr  San Diego       CA
22     Passage To India  16411 Bernardo Center Dr  San Diego       CA
23     Passage To India  16411 Bernardo Center Dr  San Diego       CA
24     Passage To India  16411 Bernardo Center Dr  San Diego       CA
25     Passage To India  16411 Bernardo Center Dr  San Diego       CA
26     Passage To India  16411 Bernardo Center Dr  San Diego       CA
27     Passage To India  16411 Bernardo Center Dr  San Diego       CA
28     Passage To India  16411 Bernardo Center Dr  San Diego       CA
29     Passage To India  16411 Bernardo Center Dr  San Diego       CA
30     Passage To India  16411 Bernardo Center Dr  San Diego       CA
31     Passage To India  16411 Bernardo Center Dr  San Diego       CA
32     Passage To India  16411 Bernardo Center Dr  San Diego       CA
33     Passage To India  16411 Bernardo Center Dr  San Diego       CA
34     Passage To India  16411 Bernardo Center Dr  San Diego       CA
35     Passage To India  16411 Bernardo Center Dr  San Diego       CA
36     Passage To India  16411 Bernardo Center Dr  San Diego       CA
37    Green Force Juice             2265 Broadway   New York       NY
38    Green Force Juice             2265 Broadway   New York       NY
39    Green Force Juice             2265 Broadway   New York       NY
40    Green Force Juice             2265 Broadway   New York       NY
41    Green Force Juice             2265 Broadway   New York       NY
42    Green Force Juice             2265 Broadway   New York       NY
43    Green Force Juice             2265 Broadway   New York       NY
44    Green Force Juice             2265 Broadway   New York       NY
45    Green Force Juice             2265 Broadway   New York       NY
46    Green Force Juice             2265 Broadway   New York       NY
47    Green Force Juice             2265 Broadway   New York       NY
48    Green Force Juice             2265 Broadway   New York       NY
49    Green Force Juice             2265 Broadway   New York       NY
50    Green Force Juice             2265 Broadway   New York       NY
51    Green Force Juice             2265 Broadway   New York       NY
52    Green Force Juice             2265 Broadway   New York       NY
53    Green Force Juice             2265 Broadway   New York       NY
54    Green Force Juice             2265 Broadway   New York       NY
55    Green Force Juice             2265 Broadway   New York       NY
56    Green Force Juice             2265 Broadway   New York       NY
57    Green Force Juice             2265 Broadway   New York       NY
58    Green Force Juice             2265 Broadway   New York       NY
59    Green Force Juice             2265 Broadway   New York       NY
60    Green Force Juice             2265 Broadway   New York       NY
61    Green Force Juice             2265 Broadway   New York       NY
62    Green Force Juice             2265 Broadway   New York       NY
63    Green Force Juice             2265 Broadway   New York       NY
64    Green Force Juice             2265 Broadway   New York       NY
65    Green Force Juice             2265 Broadway   New York       NY
66    Green Force Juice             2265 Broadway   New York       NY
67    Green Force Juice             2265 Broadway   New York       NY
68    Green Force Juice             2265 Broadway   New York       NY
69    Green Force Juice             2265 Broadway   New York       NY
70    Green Force Juice             2265 Broadway   New York       NY
71    Green Force Juice             2265 Broadway   New York       NY
72    Green Force Juice             2265 Broadway   New York       NY
73    Green Force Juice             2265 Broadway   New York       NY
74    Green Force Juice             2265 Broadway   New York       NY
75    Green Force Juice             2265 Broadway   New York       NY
76           Liquiteria               102 8th Ave   New York       NY
77           Liquiteria               102 8th Ave   New York       NY
78           Liquiteria               102 8th Ave   New York       NY
79           Liquiteria               102 8th Ave   New York       NY
80           Liquiteria               102 8th Ave   New York       NY
81           Liquiteria               102 8th Ave   New York       NY
82           Liquiteria               102 8th Ave   New York       NY
83           Liquiteria               102 8th Ave   New York       NY
84           Liquiteria               102 8th Ave   New York       NY
85           Liquiteria               102 8th Ave   New York       NY
86           Liquiteria               102 8th Ave   New York       NY
87           Liquiteria               102 8th Ave   New York       NY
88           Liquiteria               102 8th Ave   New York       NY
89           Liquiteria               102 8th Ave   New York       NY
90           Liquiteria               102 8th Ave   New York       NY
91           Liquiteria               102 8th Ave   New York       NY
92           Liquiteria               102 8th Ave   New York       NY
93           Liquiteria               102 8th Ave   New York       NY
94           Liquiteria               102 8th Ave   New York       NY
95           Liquiteria               102 8th Ave   New York       NY
96           Liquiteria               102 8th Ave   New York       NY
97           Liquiteria               102 8th Ave   New York       NY
98           Liquiteria               102 8th Ave   New York       NY
99           Liquiteria               102 8th Ave   New York       NY

                                             cuisines
1                       Thai,Asian/Pacific,Vegetarian
2                       Thai,Asian/Pacific,Vegetarian
3                       Thai,Asian/Pacific,Vegetarian
4                       Thai,Asian/Pacific,Vegetarian
5                                   Vegetarian,Indian
6                                   Vegetarian,Indian
7                                   Vegetarian,Indian
8                                   Vegetarian,Indian
9                                   Vegetarian,Indian
10                                  Vegetarian,Indian
11                                  Vegetarian,Indian
12                                  Vegetarian,Indian
13                                  Vegetarian,Indian
14                                  Vegetarian,Indian
15                                  Vegetarian,Indian
16                                  Vegetarian,Indian
17                                  Vegetarian,Indian
18                                  Vegetarian,Indian
19                                  Vegetarian,Indian
20                                  Vegetarian,Indian
21                                  Vegetarian,Indian
22                                  Vegetarian,Indian
23                                  Vegetarian,Indian
24                                  Vegetarian,Indian
25                                  Vegetarian,Indian
26                                  Vegetarian,Indian
27                                  Vegetarian,Indian
28                                  Vegetarian,Indian
29                                  Vegetarian,Indian
30                                  Vegetarian,Indian
31                                  Vegetarian,Indian
32                                  Vegetarian,Indian
33                                  Vegetarian,Indian
34                                  Vegetarian,Indian
35                                  Vegetarian,Indian
36                                  Vegetarian,Indian
37            Smoothies and Juices,Vegetarian,Healthy
38            Smoothies and Juices,Vegetarian,Healthy
39            Smoothies and Juices,Vegetarian,Healthy
40            Smoothies and Juices,Vegetarian,Healthy
41            Smoothies and Juices,Vegetarian,Healthy
42            Smoothies and Juices,Vegetarian,Healthy
43            Smoothies and Juices,Vegetarian,Healthy
44            Smoothies and Juices,Vegetarian,Healthy
45            Smoothies and Juices,Vegetarian,Healthy
46            Smoothies and Juices,Vegetarian,Healthy
47            Smoothies and Juices,Vegetarian,Healthy
48            Smoothies and Juices,Vegetarian,Healthy
49            Smoothies and Juices,Vegetarian,Healthy
50            Smoothies and Juices,Vegetarian,Healthy
51            Smoothies and Juices,Vegetarian,Healthy
52            Smoothies and Juices,Vegetarian,Healthy
53            Smoothies and Juices,Vegetarian,Healthy
54            Smoothies and Juices,Vegetarian,Healthy
55            Smoothies and Juices,Vegetarian,Healthy
56            Smoothies and Juices,Vegetarian,Healthy
57            Smoothies and Juices,Vegetarian,Healthy
58            Smoothies and Juices,Vegetarian,Healthy
59            Smoothies and Juices,Vegetarian,Healthy
60            Smoothies and Juices,Vegetarian,Healthy
61            Smoothies and Juices,Vegetarian,Healthy
62            Smoothies and Juices,Vegetarian,Healthy
63            Smoothies and Juices,Vegetarian,Healthy
64            Smoothies and Juices,Vegetarian,Healthy
65            Smoothies and Juices,Vegetarian,Healthy
66            Smoothies and Juices,Vegetarian,Healthy
67            Smoothies and Juices,Vegetarian,Healthy
68            Smoothies and Juices,Vegetarian,Healthy
69            Smoothies and Juices,Vegetarian,Healthy
70            Smoothies and Juices,Vegetarian,Healthy
71            Smoothies and Juices,Vegetarian,Healthy
72            Smoothies and Juices,Vegetarian,Healthy
73            Smoothies and Juices,Vegetarian,Healthy
74            Smoothies and Juices,Vegetarian,Healthy
75            Smoothies and Juices,Vegetarian,Healthy
76  Local/Organic,Vegan Restaurants,Smoothies and ...
77  Local/Organic,Vegan Restaurants,Smoothies and ...
78  Local/Organic,Vegan Restaurants,Smoothies and ...
79  Local/Organic,Vegan Restaurants,Smoothies and ...
80  Local/Organic,Vegan Restaurants,Smoothies and ...
81  Local/Organic,Vegan Restaurants,Smoothies and ...
82  Local/Organic,Vegan Restaurants,Smoothies and ...
83  Local/Organic,Vegan Restaurants,Smoothies and ...
84  Local/Organic,Vegan Restaurants,Smoothies and ...
85  Local/Organic,Vegan Restaurants,Smoothies and ...
86  Local/Organic,Vegan Restaurants,Smoothies and ...
87  Local/Organic,Vegan Restaurants,Smoothies and ...
88  Local/Organic,Vegan Restaurants,Smoothies and ...
89  Local/Organic,Vegan Restaurants,Smoothies and ...
90  Local/Organic,Vegan Restaurants,Smoothies and ...
91  Local/Organic,Vegan Restaurants,Smoothies and ...
92  Local/Organic,Vegan Restaurants,Smoothies and ...
93  Local/Organic,Vegan Restaurants,Smoothies and ...
94  Local/Organic,Vegan Restaurants,Smoothies and ...
95  Local/Organic,Vegan Restaurants,Smoothies and ...
96  Local/Organic,Vegan Restaurants,Smoothies and ...
97  Local/Organic,Vegan Restaurants,Smoothies and ...
98  Local/Organic,Vegan Restaurants,Smoothies and ...
99  Local/Organic,Vegan Restaurants,Smoothies and ...

In [134]:
restaurants_info_needed = restaurants_info_needed.drop_duplicates()
print(len(restaurants_info_needed))
print(restaurants_info_needed.head())

211
                        name                   address       city province  \
0        Potala Organic Cafe        1045 San Pablo Ave     Albany       CA
5           Passage To India  16411 Bernardo Center Dr  San Diego       CA
37         Green Force Juice             2265 Broadway   New York       NY
76                Liquiteria               102 8th Ave   New York       NY
386  Maggiano's Little Italy        2019 Post Oak Blvd    Houston       TX

                                              cuisines
0                        Thai,Asian/Pacific,Vegetarian
5                                    Vegetarian,Indian
37             Smoothies and Juices,Vegetarian,Healthy
76   Local/Organic,Vegan Restaurants,Smoothies and ...
386       Seafood,Italian,Vegetarian,Deli and Sandwich

In [135]:
#How many restaurants are there in each metro area?
list_of_cities = restaurants_info_needed.city.unique()
print(list_of_cities)

['Albany' 'San Diego' 'New York' 'Houston' 'Brooklyn' 'Long Island City'
 'Astoria' 'Jackson Heights' 'Torrance' 'San Francisco' 'Los Angeles'
 'Concord' 'Chicago' 'College Point' 'Bellerose' 'Glen Oaks' 'Austin'
 'Phoenix' 'Canoga Park' 'Tempe' 'Richmond' 'Newport Beach'
 'Salt Lake City' 'Encino' 'Hollywood' 'Escondido' 'Vienna' 'Westmont'
 'Boston' 'Pittsburgh' 'Woodside' 'Santa Fe' 'Miami' 'Beverly Hills'
 'Diamond Bar' 'Berkeley' 'Champaign' 'Evanston' 'South Richmond Hill'
 'Wellesley Hills' 'Charlotte' 'Penfield' 'Warren' 'Napa' 'Redmond'
 'Glendale' 'Overland Park' 'Atlanta' 'Santa Clara' 'Nashville' 'Carson'
 'Raleigh' 'Waltham' 'Seattle' 'Asbury Park' 'Cambridge' 'Tahoe City'
 'Portland' 'Dallas' 'San Jose' 'Tucson' 'Neenah' 'Arlington'
 'Minneapolis' 'Kew Gardens' 'Cary' 'Philadelphia' 'Flushing' 'Kƒ´hei'
 'Minnetonka' 'Olympia' 'Miami Beach' 'Key West' 'Rancho Santa Fe'
 'Manistee' 'Jamaica' 'Carrboro' 'Skowhegan' 'Reno' 'Walnut Creek'
 'Santa Rosa Beach']

In [136]:
city_count = restaurants_info_needed.city.value_counts()
print(city_count)

New York               66
Brooklyn               24
Chicago                 6
Los Angeles             5
San Diego               5
Houston                 4
Charlotte               3
Miami                   3
Astoria                 3
Flushing                3
Seattle                 3
Phoenix                 3
Jackson Heights         3
San Francisco           3
Bellerose               2
Torrance                2
Salt Lake City          2
Austin                  2
Portland                2
Berkeley                2
Pittsburgh              2
Woodside                2
Tempe                   2
San Jose                2
Encino                  1
Vienna                  1
South Richmond Hill     1
Albany                  1
Arlington               1
Reno                    1
Santa Clara             1
Neenah                  1
Redmond                 1
Wellesley Hills         1
Santa Rosa Beach        1
Carrboro                1
Diamond Bar             1
Manistee                1
Key West                1
Glendale                1
Newport Beach           1
Long Island City        1
Champaign               1
Olympia                 1
Santa Fe                1
Raleigh                 1
Penfield                1
Waltham                 1
Kƒ´hei                  1
Tucson                  1
Richmond                1
Beverly Hills           1
Napa                    1
Boston                  1
Skowhegan               1
Philadelphia            1
College Point           1
Hollywood               1
Westmont                1
Escondido               1
Cambridge               1
Jamaica                 1
Asbury Park             1
Overland Park           1
Concord                 1
Nashville               1
Dallas                  1
Minnetonka              1
Warren                  1
Kew Gardens             1
Cary                    1
Minneapolis             1
Evanston                1
Glen Oaks               1
Carson                  1
Atlanta                 1
Miami Beach             1
Walnut Creek            1
Tahoe City              1
Rancho Santa Fe         1
Canoga Park             1
Name: city, dtype: int64

In [146]:
#How many restaurants in each metro area offers vegetarian options?
vegetarian_restaurants = restaurants_info_needed[restaurants_info_needed.cuisines == 'Vegetarian']
print(vegetarian_restaurants)
#doesn't show all restaurants.Need a different code. 
#only shows up as vegetarian if vegetarian is the only thing listed in cuisine.

                 name                 address         city province  \
4580      Vegan House      2703 W Sunset Blvd  Los Angeles       CA
5895     Veggie Grill  2533 Pacific Coast Hwy     Torrance       CA
7357  The Last Carrot          3133 Grand Ave        Miami       FL
8447        Le Voyeur           404 4th Ave E      Olympia       WA
8912         The Cafe         509 Southard St     Key West       FL

        cuisines
4580  Vegetarian
5895  Vegetarian
7357  Vegetarian
8447  Vegetarian
8912  Vegetarian

In [147]:
vegetarian_restaurants_2 = restaurants_info_needed[restaurants_info_needed.cuisines.str.contains('Vegetarian')]
print(vegetarian_restaurants_2.head())

                        name                   address       city province  \
0        Potala Organic Cafe        1045 San Pablo Ave     Albany       CA
5           Passage To India  16411 Bernardo Center Dr  San Diego       CA
37         Green Force Juice             2265 Broadway   New York       NY
76                Liquiteria               102 8th Ave   New York       NY
386  Maggiano's Little Italy        2019 Post Oak Blvd    Houston       TX

                                              cuisines
0                        Thai,Asian/Pacific,Vegetarian
5                                    Vegetarian,Indian
37             Smoothies and Juices,Vegetarian,Healthy
76   Local/Organic,Vegan Restaurants,Smoothies and ...
386       Seafood,Italian,Vegetarian,Deli and Sandwich

In [139]:
Vegetarian_by_city = vegetarian_restaurants_2.city.value_counts()
print(Vegetarian_by_city)
#Result makes sense as all vegan restaurants are vegetarian so essentially all restaurants on list should be vegetarian.

New York               66
Brooklyn               21
San Diego               5
Los Angeles             5
Chicago                 5
Houston                 4
Flushing                3
Astoria                 3
Phoenix                 3
Jackson Heights         3
Charlotte               3
San Francisco           3
Salt Lake City          2
Torrance                2
Portland                2
Seattle                 2
Berkeley                2
Miami                   2
Pittsburgh              2
Woodside                2
Bellerose               2
Tempe                   2
San Jose                2
Key West                1
Albany                  1
Arlington               1
Reno                    1
Neenah                  1
Redmond                 1
Austin                  1
Wellesley Hills         1
Carrboro                1
Overland Park           1
Manistee                1
Vienna                  1
Glendale                1
Philadelphia            1
Santa Rosa Beach        1
Newport Beach           1
Champaign               1
Olympia                 1
Santa Fe                1
Raleigh                 1
Penfield                1
Waltham                 1
Long Island City        1
Kƒ´hei                  1
Tucson                  1
Richmond                1
South Richmond Hill     1
Encino                  1
Napa                    1
Boston                  1
College Point           1
Hollywood               1
Westmont                1
Escondido               1
Cambridge               1
Jamaica                 1
Asbury Park             1
Concord                 1
Atlanta                 1
Nashville               1
Dallas                  1
Minnetonka              1
Warren                  1
Kew Gardens             1
Canoga Park             1
Minneapolis             1
Cary                    1
Glen Oaks               1
Carson                  1
Evanston                1
Miami Beach             1
Walnut Creek            1
Tahoe City              1
Rancho Santa Fe         1
Skowhegan               1
Beverly Hills           1
Name: city, dtype: int64

In [148]:
#How many restaurants in each metro area offers vegan options?
vegan_restaurants = restaurants_info_needed[restaurants_info_needed.cuisines.str.contains('Vegan')]
print(vegan_restaurants.head())

                           name          address      city province  \
76                   Liquiteria      102 8th Ave  New York       NY
477              Frappe 'n Wrap    1702 Avenue M  Brooklyn       NY
558           Clementine Bakery  395 Classon Ave  Brooklyn       NY
570                     Mudspot     307 E 9th St  New York       NY
773  Tu-Lu's Gluten-Free Bakery    338 E 11th St  New York       NY

                                              cuisines
76   Local/Organic,Vegan Restaurants,Smoothies and ...
477                                 Sushi,Kosher,Vegan
558                 Desserts,Bakery and Pastries,Vegan
570  American (New),Vegetarian,Coffee and Tea,Healt...
773  Vegetarian,Coffee and Tea,Bakery,Desserts,Bake...

In [149]:
vegan_by_city = vegan_restaurants.city.value_counts()
print(vegan_by_city)

New York            7
Brooklyn            6
Seattle             2
Chicago             2
Champaign           1
Torrance            1
Philadelphia        1
Berkeley            1
Pittsburgh          1
Cambridge           1
Neenah              1
Asbury Park         1
Miami               1
Warren              1
Portland            1
Houston             1
Carson              1
Skowhegan           1
Austin              1
Phoenix             1
Arlington           1
Long Island City    1
Newport Beach       1
Los Angeles         1
Santa Rosa Beach    1
Charlotte           1
Santa Clara         1
Richmond            1
Tahoe City          1
Beverly Hills       1
San Francisco       1
San Diego           1
Salt Lake City      1
Evanston            1
Concord             1
Diamond Bar         1
Name: city, dtype: int64